Author : Doki Sai Vamsee

In [2]:
import numpy as np
import pandas as pd

### 1. How to import pandas and check the version?

In [1]:
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))

1.4.3
{
  "system": {
    "commit": "e8093ba372f9adfe79439d90fe74b0b5b6dea9d6",
    "python": "3.9.13.final.0",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19044",
    "machine": "AMD64",
    "processor": "Intel64 Family 6 Model 23 Stepping 10, GenuineIntel",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "English_India",
      "encoding": "1252"
    }
  },
  "dependencies": {
    "pandas": "1.4.3",
    "numpy": "1.23.1",
    "pytz": "2022.1",
    "dateutil": "2.8.2",
    "setuptools": "58.1.0",
    "pip": "22.0.4",
    "Cython": null,
    "pytest": null,
    "hypothesis": null,
    "sphinx": null,
    "blosc": null,
    "feather": null,
    "xlsxwriter": null,
    "lxml.etree": null,
    "html5lib": null,
    "pymysql": null,
    "psycopg2": null,
    "jinja2": "3.1.2",
    "IPython": "8.4.0",
    "pandas_datareader": null,
    "bs4": "4.11.1",
    "bottleneck": null,
    "brotli": nu

### 2. How to create a series from a list, numpy array and dict?

In [3]:
import numpy as np
import pandas as pd

a = list('sairam')
b = np.arange(6)
c = dict(zip(a,b))

series1 = pd.Series(a)
series2 = pd.Series(b)
series3 = pd.Series(c)

print(series3)

s    0
a    4
i    2
r    3
m    5
dtype: int32


### 3. How to convert the index of a series into a column of a dataframe?

In [65]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


### 4. How to combine many series to form a dataframe?

In [7]:
import pandas as pd

series = {
    "names":['sai','ram','krishna','rocky'],
    "weight":[55,85,60,78]
}

temp = pd.DataFrame(series)

print(temp)

     names  weight
0      sai      55
1      ram      85
2  krishna      60
3    rocky      78


### 5. How to assign name to the series’ index?

In [13]:
a = pd.Series([34.0,35.6,20.8,40.5])

a.name = 'Temperatures'
print(a)

0    34.0
1    35.6
2    20.8
3    40.5
Name: Temperatures, dtype: float64


### 6.How to get the items of series A not present in series B?

In [11]:
import pandas as pd

a = pd.Series([12,23,45,56,78,89])
b = pd.Series([12,54,65,23,89,87])

print('series 1 :')
print(a)
print('\nseries 2 :')
print(b)

print("Items in 'a' that are not present in 'b' :")
c = a[~a.isin(b)]
print(c)

series 1 :
0    12
1    23
2    45
3    56
4    78
5    89
dtype: int64

series 2 :
0    12
1    54
2    65
3    23
4    89
5    87
dtype: int64
Items in 'a' that are not present in 'b' :
2    45
3    56
4    78
dtype: int64


### 7. How to get the items not common to both series A and series B?


In [15]:
a = pd.Series([1,2,3,4,5,6,7,8,9])
b = pd.Series([1,23,4,56,7,89,9,87,5])

print('series 1 :')
print(a)
print('\nseries 2 :')
print(b)

#union
temp = pd.Series(np.union1d(a,b))

#intersection
temp2 = pd.Series(np.intersect1d(a,b))

#getting uncommon elements
uncom = temp[~temp.isin(temp2)]

print(uncom)

series 1 :
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

series 2 :
0     1
1    23
2     4
3    56
4     7
5    89
6     9
7    87
8     5
dtype: int64
1      2
2      3
5      6
7      8
9     23
10    56
11    87
12    89
dtype: int64


### 8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [16]:
state = np.random.RandomState(500)
a = pd.Series(state.normal(10, 5, 25))

# Solution
np.percentile(a, q=[0, 25, 50, 75, 100])

array([-0.44533179,  6.20060621,  9.59564845, 13.41401188, 19.60689387])

### 9. How to get frequency counts of unique items of a series?

In [19]:
a = pd.Series([1,2,3,1,5,4,2,9,8,7,6,5])
 
print(a)
print(a.value_counts())

0     1
1     2
2     3
3     1
4     5
5     4
6     2
7     9
8     8
9     7
10    6
11    5
dtype: int64
1    2
2    2
5    2
3    1
4    1
9    1
8    1
7    1
6    1
dtype: int64


### 10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [22]:
series = pd.Series([1,2,3,1,5,4,2,9,8,7,6,5])
  
freq = series.value_counts()
  
series[~series.isin(freq .index[:2])] = 'other'
print(series)

0         1
1         2
2     other
3         1
4     other
5     other
6         2
7     other
8     other
9     other
10    other
11    other
dtype: object


### 12. How to convert a numpy array to a dataframe of given shape? (L1)

In [23]:
array = np.array([[15, 22, 43], 
                  [33, 24, 56]])

temp = pd.DataFrame(array)


print(temp)

    0   1   2
0  15  22  43
1  33  24  56


### 13. How to find the positions of numbers that are multiples of 3 from a series?

In [80]:
ser = pd.Series(np.random.randint(1,5,5))

print(ser)

np.argwhere(ser % 3==0)

0    1
1    3
2    1
3    4
4    3
dtype: int32


ValueError: Length of values (1) does not match length of index (5)

### 14. How to extract items at given positions from a series

In [16]:
a = pd.Series([1,2,3,1,5,4,2,9,8,7,6,5])
pos = [0,3,6,10]

a.take(pos)

0     1
3     1
6     2
10    6
dtype: int64

### 15. How to stack two series vertically and horizontally ?

In [24]:
a = pd.Series(['S','a','i','r','a','m',])
b = pd.Series([1,2,3,4,5,6])

print('vertical Stack')
print(pd.concat([a,b],axis = 0))

print('Horizontal stack')
print(pd.concat([a,b],axis = 1))

vertical Stack
0    S
1    a
2    i
3    r
4    a
5    m
0    1
1    2
2    3
3    4
4    5
5    6
dtype: object
Horizontal stack
   0  1
0  S  1
1  a  2
2  i  3
3  r  4
4  a  5
5  m  6


### 16. How to get the positions of items of series A in another series B?


In [27]:
a = pd.Series([1,2,3,1,5,4,2,9,8,7,6,5])
b = pd.Series([1,3,5,7,9])

print("Positions of items of b in a:")
[pd.Index(a).get_loc(i) for i in b]

Positions of items of b in a:


[array([ True, False, False,  True, False, False, False, False, False,
        False, False, False]),
 2,
 array([False, False, False, False,  True, False, False, False, False,
        False, False,  True]),
 9,
 7]

### 17. How to compute the mean squared error on a truth and predicted series?

In [6]:
truth = pd.Series(range(10))
pred = pd.Series(range(10) + np.random.random(10))

np.mean((truth-pred)**2)

0.4217816206589683

### 18. How to convert the first character of each element in a series to uppercase?

In [10]:
a = pd.Series(['sairam','brothers','welcome','to','pandas'])

a.map(lambda x: x.title())
a.map(lambda x: x[0].upper() + x[1:])
pd.Series([i.title() for i in a])

0      Sairam
1    Brothers
2     Welcome
3          To
4      Pandas
dtype: object

### 19. How to calculate the number of characters in each word in a series?

In [11]:
x = pd.Series(['python','pandas','numpy'])

x.map(lambda x: len(x))

0    6
1    6
2    5
dtype: int64

### 20. How to compute difference of differences between consequtive numbers of a series?

In [12]:
a = pd.Series([1,2,3,4,5,6,7,8,9])

print(a.diff().tolist())
print(a.diff().diff().tolist())

[nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


### 21. How to convert a series of date-strings to a timeseries?

In [23]:
dates = pd.Series(['06 Jan 1978', '20120102', '20120303', '2013/04/04', '2014-05-15', '2015-06-06T12:20'])
from dateutil.parser import parse
dates.map(lambda x: parse(x))

0   1978-01-06 00:00:00
1   2012-01-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-15 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

### 22. How to get the day of month, week number, day of year and day of week from a series of date strings?

In [33]:
dates = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2015-06-06T12:20'])

from dateutil.parser import parse
temp = dates.map(lambda x: parse(x))

print("Date: ", temp.dt.day.tolist())

print("Day number of year: ", temp.dt.dayofyear.tolist())


Date:  [1, 2, 3, 4, 6]
Day number of year:  [1, 33, 63, 94, 157]


### 23. How to convert year-month string to dates corresponding to the 4th day of the month?

In [71]:
from dateutil.parser import parse

ser = pd.Series(['Jan 2020', 'Feb 2021', 'Mar 2022'])


ser_ts = ser.map(lambda x: parse(x))
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]


['2020-01-04', '2021-02-04', '2022-03-04']

### 24. How to filter words that contain atleast 2 vowels from a series?

In [72]:
from collections import Counter

a = pd.Series(['Muddenahalli', 'Chikballapur', 'Karnataka', 'Bengaluru', 'India'])

mask = a.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
a[mask]

0    Muddenahalli
1    Chikballapur
2       Karnataka
3       Bengaluru
4           India
dtype: object

### 26. How to get the mean of a series grouped by another series?

In [39]:
Students_names = pd.Series(np.random.choice(['joy', 'key', 'ham','sam'], 10))

marks= pd.Series(np.linspace(1, 100, 10))

print(Students_names.tolist())
print(marks.tolist())

marks.groupby(Students_names).mean()

['key', 'joy', 'joy', 'sam', 'key', 'ham', 'sam', 'key', 'ham', 'sam']
[1.0, 12.0, 23.0, 34.0, 45.0, 56.0, 67.0, 78.0, 89.0, 100.0]


ham    72.500000
joy    17.500000
key    41.333333
sam    67.000000
dtype: float64

### 27. How to compute the euclidean distance between two series?

In [40]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([11,12,13,14,15,16,17,18,19,20])

sum((p - q)**2)**.5


31.622776601683793

### 28. How to find all the local maxima (or peaks) in a numeric series?

In [44]:
w = pd.Series(np.random.randint(1, 5, 10))
print(w)
y = np.diff(np.sign(np.diff(w)))
peak_locs = np.where(y == -2)[0] + 1
peak_locs

0    3
1    1
2    3
3    2
4    2
5    2
6    3
7    4
8    1
9    3
dtype: int32


array([2, 7], dtype=int64)

### 29. How to replace missing spaces in a string with the least frequent character?

In [49]:
a = pd.Series(list('sdd sfs bgf gfer he sgaeir fbajwew'))

frequency = a.value_counts()
print(frequency)

least_freq = frequency.dropna().index[-1]
"".join(a.replace(' ', least_freq))

     6
s    4
f    4
e    4
g    3
d    2
b    2
r    2
a    2
w    2
h    1
i    1
j    1
dtype: int64


'sddjsfsjbgfjgferjhejsgaeirjfbajwew'

### 32. How to compute the autocorrelations of a numeric series?

In [51]:
a = pd.Series(np.arange(10) + np.random.normal(1, 5, 10))

autocorrelations = [a.autocorr(i).round(2) for i in range(9)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.38, 0.15, 0.42, 0.26, 0.56, 0.08, -0.86, 1.0]
Lag having highest correlation:  8


### 33. How to import only every nth row from a csv file to create a dataframe?

In [9]:
df = pd.read_csv('meal_info.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
df2

meal_id   category      cuisine
0     1885  Beverages         Thai
50    1445    Seafood  Continental

### 34. How to change column values when importing csv to a dataframe?

In [15]:
df = pd.read_csv('fulfilment_center_info.csv',converters={'region_code': lambda x: 'South' if float(x) > 50 else 'North'})
df

center_id  city_code region_code center_type  op_area
0          11        679       South      TYPE_A      3.7
1          13        590       South      TYPE_B      6.7
2         124        590       South      TYPE_C      4.0
3          66        648       North      TYPE_A      4.1
4          94        632       North      TYPE_C      3.6
..        ...        ...         ...         ...      ...
72         53        590       South      TYPE_A      3.8
73         30        604       South      TYPE_A      3.5
74         76        614       South      TYPE_A      3.0
75         68        676       North      TYPE_B      4.1
76         51        638       South      TYPE_A      7.0

[77 rows x 5 columns]

### 36. How to import only specified columns from a csv file?

In [16]:
df = pd.read_csv('fulfilment_center_info.csv', usecols=['city_code', 'op_area'])
print(df.head())

   city_code  op_area
0        679      3.7
1        590      6.7
2        590      4.0
3        648      4.1
4        632      3.6


### 37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.

In [26]:
df = pd.read_csv('fulfilment_center_info.csv')

print('number of rows and colums in the data :',df.shape)   # gives the number of columns and rows

print('\ndatatypes of various attributes :')
print(df.dtypes)                           # gives the datatypes

print('\n the value counts of each attribute:')
print(df.dtypes.value_counts())            # Specifies how many columns are there under each datatype

print('\nthe overall statistics of the data is :')
data_statistics = df.describe()            # summary statistics
print(data_statistics)

data_array = df.values                     # numpy array
print(data_array)

data_list = df.values.tolist()             # list
print(data_list)

number of rows and colums in the data : (77, 5)

datatypes of various attributes :
center_id        int64
city_code        int64
region_code      int64
center_type     object
op_area        float64
dtype: object

 the value counts of each attribute:
int64      3
object     1
float64    1
dtype: int64

the overall statistics of the data is :
        center_id   city_code  region_code    op_area
count   77.000000   77.000000    77.000000  77.000000
mean    83.142857  600.662338    56.493506   3.985714
std     46.090219   66.720274    18.126473   1.106406
min     10.000000  456.000000    23.000000   0.900000
25%     50.000000  553.000000    34.000000   3.500000
50%     77.000000  596.000000    56.000000   3.900000
75%    110.000000  651.000000    77.000000   4.400000
max    186.000000  713.000000    93.000000   7.000000
[[11 679 56 'TYPE_A' 3.7]
 [13 590 56 'TYPE_B' 6.7]
 [124 590 56 'TYPE_C' 4.0]
 [66 648 34 'TYPE_A' 4.1]
 [94 632 34 'TYPE_C' 3.6]
 [64 553 77 'TYPE_A' 4.4]
 [129 593 77 '

### 39. How to rename a specific columns in a dataframe?

In [28]:
df = pd.read_csv('meal_info.csv')
print(df.columns)
df=df.rename(columns = {'meal_id':'Food_id'})
print(df.columns)

Index(['meal_id', 'category', 'cuisine'], dtype='object')
Index(['Food_id', 'category', 'cuisine'], dtype='object')


### 40. How to check if a dataframe has any missing values?

In [29]:
df = pd.read_csv('meal_info.csv')
df.isnull().values.any()

False

### 41. How to count the number of missing values in each column?

In [30]:
df = pd.read_csv('meal_info.csv')
missing_col = df.apply(lambda x: x.isnull().sum())
missing_col.argmax()

0

### 44. How to select a specific column from a dataframe as a dataframe instead of a series?

In [45]:
df = pd.DataFrame(np.arange(6).reshape(-1, 6), columns=list('sairam'))

type(df[['s']])
type(df.loc[:, ['s']])
type(df.iloc[:, [0]])
pd.core.series.Series
df

s  a  i  r  a  m
0  0  1  2  3  4  5

### 46. How to set the number of rows and columns displayed in the output?

In [52]:
df = pd.read_csv('train.csv')

pd.set_option('display.max_columns', 5)
pd.set_option('display.max_rows', 5)

df

id  week  ...  homepage_featured  num_orders
0       1379560     1  ...                  0         177
1       1466964     1  ...                  0         270
...         ...   ...  ...                ...         ...
456546  1147725   145  ...                  0         729
456547  1361984   145  ...                  0         162

[456548 rows x 9 columns]

### 48. How to format all the values in a dataframe as percentages?

In [53]:
df = pd.DataFrame(np.random.random(10), columns=['random_percentages'])

out = df.style.format({'random_percentages': '{0:.5%}'.format,})

out

### 49. How to filter every nth row in a dataframe?

In [68]:
df = pd.read_csv('meal_info.csv')
print(df.iloc[::3, :][['meal_id', 'category', 'cuisine']])

    meal_id   category      cuisine
0      1885  Beverages         Thai
3      1248  Beverages       Indian
..      ...        ...          ...
45     1571       Fish  Continental
48     2444    Seafood  Continental

[17 rows x 3 columns]


### 51. How to get the row number of the nth largest value in a column?

In [80]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

n = 9
df['a'].argsort()[::-1][n]

1

### 52. How to find the position of the nth largest value greater than a given value?

In [93]:
a = pd.Series(np.random.randint(1, 50, 9))

print('a: ', a.tolist(), 'mean: ', round(a.mean()))
np.argwhere(a > a.mean())

a:  [16, 35, 43, 2, 17, 9, 6, 18, 34] mean:  20


ValueError: Length of values (1) does not match length of index (9)

### 53. How to get the last n rows of a dataframe with row sum > 100?

In [5]:
df = pd.DataFrame(np.random.randint(1, 50, 30).reshape(-1, 10))

rowsums = df.apply(np.sum, axis=1)

last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]

print(last_two_rows)

    0   1   2   3   4   5   6   7   8   9
1  19   2  48   3  35  30   8  22  38  11
2   3  12  23  46  42   4  42  12  16   6


### 56. How to swap two rows of a dataframe?

In [12]:
df = pd.DataFrame(np.arange(100).reshape(10, -1))

def swap_two_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

swap_two_rows(df, 1, 2)

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  20  21  22  23  24  25  26  27  28  29
2  10  11  12  13  14  15  16  17  18  19
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

### 57. How to reverse the rows of a dataframe?

In [14]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df)
print('\ndata after reversing the rows')
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

data after reversing a row
    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


### 59. Which column contains the highest number of row-wise maximum values?

In [20]:
df = pd.DataFrame(np.random.randint(1, 50, 20).reshape(5, -1))

print(df)

row_max = df.apply(np.argmax, axis=1).value_counts().index[0]

print('Column with highest row maxes: ',row_max)

    0   1   2   3
0  12   5   8  16
1   6  10  25  20
2  47   9  26  39
3  26   7  24  18
4  21  14   2  46
Column with highest row maxes:  3


### 62. How to create a column containing the minimum by maximum of each row?

In [29]:
df = pd.DataFrame(np.random.randint(1,10, 25).reshape(5, -1))

print(df)
print('\nThe column containg the minimum by maximum of each row is :')
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

print(min_by_max)

   0  1  2  3  4
0  7  3  1  3  5
1  2  1  3  1  9
2  8  1  7  8  4
3  3  9  6  9  7
4  3  1  3  6  2

The column containg the minimum by maximum of each row is :
0    0.142857
1    0.111111
2    0.125000
3    0.333333
4    0.166667
dtype: float64


### 66. How to replace both the diagonals of dataframe with 0?

In [45]:
df = pd.DataFrame(np.random.randint(1,5,9).reshape(3, -1))

print(df)

for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
    
print('\nmatrix after making the diagnol elements o :' )
print(df)

   0  1  2
0  1  2  4
1  4  2  2
2  2  4  3

matrix after making the diagnol elements o :
   0  1  2
0  0  2  0
1  4  0  2
2  0  4  0


### 71. How to remove rows from a dataframe that are present in another dataframe?

In [49]:
df1 = np.random.randint(1,5,16).reshape(4, -1)

print('data_1 : ')
print(df1)
df2 = np.random.randint(1,5,16).reshape(4, -1)

print('\ndata_2 :')
print(df2)

print(df1[~df1.isin(df2).all(1)])

data_1 : 
[[1 3 3 2]
 [4 1 3 1]
 [1 1 3 4]
 [4 4 1 2]]

data_2 :
[[1 3 2 4]
 [3 4 4 3]
 [1 4 3 1]
 [2 2 4 3]]


AttributeError: 'numpy.ndarray' object has no attribute 'isin'

### 72. How to get the positions where values of two columns match?

In [52]:
df1 = np.random.randint(1,5,16).reshape(4, -1)

print('data_1 : ')
print(df1)
df2 = np.random.randint(1,5,16).reshape(4, -1)

print('\ndata_2 :')
print(df2)

np.where(df1 == df2)

data_1 : 
[[4 1 1 2]
 [3 4 2 2]
 [2 2 4 1]
 [3 4 4 1]]

data_2 :
[[2 4 2 3]
 [2 1 1 2]
 [1 2 4 4]
 [2 4 2 2]]


(array([1, 2, 2, 3], dtype=int64), array([3, 1, 2, 1], dtype=int64))

### 74. How to get the frequency of unique values in the entire dataframe?

In [55]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4))

print(df)

pd.value_counts(df.values.ravel())

   0  1  2  3
0  8  3  1  3
1  1  4  1  2
2  1  5  7  7
3  1  4  6  6
4  7  5  2  2


1    5
2    3
7    3
3    2
4    2
5    2
6    2
8    1
dtype: int64